baseURL = 'https://tdard.github.io/weekly-tech'
languageCode = 'fr-FR'
title = 'Weekly tech'
theme = 'ananke'

Paginate = 10
summaryLength = 40
googleAnalytics="G-T71NF1Y3JC"
[params]
    favicon = "favicon.ico"
